name: Bug report
description: Report a reproducible bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include commands, inputs, and expected vs actual behavior.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Node version, package versions
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/screenshots
      description: Paste logs or attach screenshots.
